
import './globals.css'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
const inter = Inter({ subsets: ['latin'] })
import { neobrutalism } from "@clerk/themes";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClerkProvider appearance={{
          baseTheme: neobrutalism
        }}>
          {children}
        </ClerkProvider>
      </body>
    </html>
  )
}
